---
# tasks file for cornerstone:discover-ip-libvirt.yml

#
# -----------------------------------------------------------------------------
# Create a dynamice inventory based on Virtual Machine IP Address
# -----------------------------------------------------------------------------
#

- name: "Debugging"
  debug:
    msg: "{{ cornerstone_vm_ip }}"

- name: "[Cornerstone - VM] Register IP with Temporary Host Group"
  add_host:
    hostname: "{{ cornerstone_vm_ip }}"
    groupname: "{{ cornerstone_prefix }}"
    ansible_ssh_user: "{{ cornerstone_ssh_user }}"
    ansible_ssh_private_key_file: "{{ cornerstone_ssh_key_path }}"
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  when: 
    - cornerstone_vm_ip != "127.0.0.1"

- name: "[Cornerstone - VM] Register IP with Temporary Host Group named after the Purpose tag"
  add_host:
    hostname: "{{ cornerstone_vm_ip }}"
    groupname: "{{ cornerstone_tag_purpose }}"
    ansible_ssh_user: "{{ cornerstone_ssh_user }}"
    ansible_ssh_private_key_file: "{{ cornerstone_ssh_key_path }}"
    ansible_ssh_extra_args: "{{ cornerstone_ssh_extra_args }}"
  when:   
    - cornerstone_tag_purpose != ""
    - cornerstone_vm_ip != "127.0.0.1"

- name: "[Cornerstone - VM] Register IP with Temporary Host Group named after the Role tag"
  add_host:
    hostname: "{{ cornerstone_vm_ip }}"
    groupname: "{{ cornerstone_tag_role }}"
    ansible_ssh_user: "{{ cornerstone_ssh_key_path }}" 
    ansible_ssh_private_key_file: "{{ cornerstone_ssh_key_path }}"
    ansible_ssh_extra_args: "{{ cornerstone_ssh_extra_args }}"
  when:
    - cornerstone_tag_role != ""
    - cornerstone_vm_ip != "127.0.0.1"
